name: iOS CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: '12.x'  # Set your desired Xcode version

      - name: Install Dependencies
        run: |
          bundle install
          bundle exec pod install

      - name: Build and Test
        run: xcodebuild -workspace YourProject.xcworkspace -scheme YourScheme -destination 'platform=iOS Simulator,name=iPhone 12' build test
